In [110]:
# NOTE: Data Analysis part 
# Why we need data analysis 
# -> In Real Time the data is in raw format 
# -> this raw format should be changed into clean format without noise , outliers and duplicate(redundant) data 
# -> 1] First we need to understand the data 
# -> 2]then we need to transform the raw data 

# NOTE: Why pandas is used 
# -> pandas library helps to hadle large amount of data efficiently unlike normal python where you need to write everything from scratch 
# if you are using pip you can install pandas by doing pip install pandas
# Since i am in arch linux i am using uv to create a virtual environment to differentiate pacman packages and python packages so i will be using uv to install python packagaes 
# The syntax will be uv pip install pandas

In [111]:
import pandas as pd 
print(pd.__version__)

3.0.5

In [112]:
# Similar to one D and two D 
# oneD means one column it is called a series 

marks = pd.Series([85,90,70,80],name='marks')
print("Marks : \n",marks)
print()
print("3rd row element and datatype of elements : ",marks[3],marks.dtype) # you can access the series elements using the index just like in the array here you will be mentioning the row index to that that row value 
print()

# series with index 
marks = pd.Series([80,90,75],index=["Ravi","Priya","Arjun"])
print("Marks of Arjun : ",marks["Arjun"])
print()

# Creating and adding a dictonary 
dict_demo = {
    "laptop" : 1500,
    "iphone" : 1200,
    "macbook" : 1700,
    "andorid_phone" : 800
}
inventory_series = pd.Series(dict_demo)
print("After Converting Dictonary into Series : ")
print(inventory_series)
print("Price of a laptop : ",inventory_series["laptop"])

# NOTE: Task on series 
student_dict = {
    "Alice" : 85,
    "Bob" : 92,
    "Charile"  :78 ,
    "David" : 95,
    "Eva" : 88
}

"""
Using *Pandas Series*, perform the following:
✅ Create a Series named scores using the dictionary student_scores.
✅ Print the marks scored by *"Charlie"* and *"Eva"*.
✅ Add *5 bonus marks* to all students and print the updated Series.
✅ Display only the students who scored *above 90* after the bonus.
✅ Calculate and print the *average marks* of the class (after the bonus).
"""
scores = pd.Series(student_dict)
print("Marks of Charile : ",scores["Charile"])
print("Marks of Eva : ",scores['Eva'])
scores = scores + 5 
print("Updated Marks :\n",scores)
result = scores[scores > 90]
print("Students with marks > 90 : \n",result)
print("Average Marks of the Students : ",scores.mean())

Marks :
 0    85
1    90
2    70
3    80
Name: marks, dtype: int64

3rd row element and datatype of elements :  80 int64

Marks of Arjun :  75

After Converting Dictonary into Series :
laptop           1500
iphone           1200
macbook          1700
andorid_phone     800
dtype: int64
Price of a laptop :  1500
Marks of Charile :  78
Marks of Eva :  88
Updated Marks :
 Alice       90
Bob         97
Charile     83
David      100
Eva         93
dtype: int64
Students with marks > 90 :
 Bob       97
David    100
Eva       93
dtype: int64
Average Marks of the Students :  92.6

In [113]:
# twoD means two columns it is called a Data Frame 
# It is the main pandas object that is used for tabular data 
# Files like excel and pdf are loaded using DataFrame 

data = pd.DataFrame([[10,20,30],[40,50,60]],dtype=float)
print(data)
print(data[1][1],data[1][1].dtype)

# From a list of lists 
data = [
    ["Ravi",21,85],
    ["Priya",20,92],
    ["Arun",22,76]
]
arr = pd.DataFrame(data,columns=["Name","Age","Marks"])
print("Marks of Ravi : ",arr[arr["Name"] == "Ravi"]["Marks"])

# From a numpy array 
import numpy as np 
arr = np.array([[1,80],[2,90],[3,75]])
data = pd.DataFrame(arr,columns=["StudentID","Marks"])
print(data)

# NOTE: Task 

a_dict = {
    'name': {'Ru': 'Rukshan', 'Pr': 'Prasadi', 'Gi': 'Gihan', 'Ha': 'Hansana'},
    'age': {'Ru': 25, 'Pr': 25, 'Gi': 26, 'Ha': 24},
    'marks': {'Ru': 85, 'Pr': 90, 'Gi': 70, 'Ha': 80}
}
 
df = pd.DataFrame(a_dict)
print(df)

      0     1     2
0  10.0  20.0  30.0
1  40.0  50.0  60.0
50.0 float64
Marks of Ravi :  0    85
Name: Marks, dtype: int64
   StudentID  Marks
0          1     80
1          2     90
2          3     75
       name  age  marks
Ru  Rukshan   25     85
Pr  Prasadi   25     90
Gi    Gihan   26     70
Ha  Hansana   24     80

In [114]:
import pandas as pd
 
ser1 = pd.Series(['Rukshan', 'Prasadi', 'Gihan', 'Hansana'], index=['Ru', 'Pr', 'Gi', 'Ha'])
ser2 = pd.Series([25, 25, 26, 24], index=['Ru', 'Pr', 'Gi', 'Ha'])
ser3 = pd.Series([85, 90, 70, 80], index=['Ru', 'Pr', 'Gi', 'Ha'])
 
a_dict = {
    'name': ser1,
    'age': ser2,
    'marks': ser3
}
 
df = pd.DataFrame(a_dict)
print(df)

# Details of the Students with highest marks 
highest_marks = max(df["marks"])
print("Name , Age , Marks of the Highest Marks : \n",df[df['marks'] == highest_marks])

# Add a new stundent "Tharushi" with age 23 and marks 88 using the index "Th"
df.loc["Th"] = ["Tharushi",23,88]
print(df)

# Display the details of the students who are 25 years old or older 
print("Students who's age is >= 25 : \n",df[df["age"] >= 25])

# Increase the marks of the students below 80 by 10 points 
df.loc[df["marks"] < 80, "marks"] += 10
print(df)

# Calucate and print the average marks of all students after the bonus 
average = df["marks"].mean()
print("Average marks after bonus:", average)

       name  age  marks
Ru  Rukshan   25     85
Pr  Prasadi   25     90
Gi    Gihan   26     70
Ha  Hansana   24     80
Name , Age , Marks of the Highest Marks :
        name  age  marks
Pr  Prasadi   25     90
        name  age  marks
Ru   Rukshan   25     85
Pr   Prasadi   25     90
Gi     Gihan   26     70
Ha   Hansana   24     80
Th  Tharushi   23     88
Students who's age is >= 25 :
        name  age  marks
Ru  Rukshan   25     85
Pr  Prasadi   25     90
Gi    Gihan   26     70
        name  age  marks
Ru   Rukshan   25     85
Pr   Prasadi   25     90
Gi     Gihan   26     80
Ha   Hansana   24     80
Th  Tharushi   23     88
Average marks after bonus: 84.6

In [115]:
# opening the csv file 
df = pd.read_csv("Student_Performance.csv")
# Loading the first five rows 
df.head(10) # methion the number of rows to be displayed

,Student_ID,Name,Age,Gender,Department,Attendance,Study_Hours,Assignment_Score,Exam_Score,City,Enrollment_Date,Fee_Status,Placement_Status
0,1001,Ravi,21,Female,Data Science,84.0,5.5,63,78,Visakhapatnam,2026-01-05,Paid,Placed
1,1002,Priya,23,Male,Cloud,76.1,8.4,61,99,Chennai,2026-01-08,Paid,Placed
2,1003,Arun,23,Female,Python,98.9,2.0,63,70,Hyderabad,2026-01-11,Paid,Placed
3,1004,Meena,21,Male,Data Science,97.9,3.6,72,64,Visakhapatnam,2026-01-14,Paid,Not Placed
4,1005,Kiran,22,Male,AI,NaN,2.8,70,76,Vijayawada,2026-01-17,Paid,Placed
5,1006,Suresh,20,Female,AI,95.4,3.4,81,77,Chennai,2026-01-20,Paid,Not Placed
6,1007,Anjali,24,Female,AI,73.8,4.9,70,74,Hyderabad,2026-01-23,Paid,Placed
7,1008,Rahul,20,Male,ai,76.6,4.1,97,91,Vijayawada,2026-01-26,Pending,Placed
8,1009,Divya,20,Female,Data Science,89.7,4.3,67,77,Vijayawada,2026-01-29,Paid,Not Placed
9,1010,Rahul,22,Female,Python,94.2,7.4,53,84,Bengaluru,2026-02-01,Paid,Not Placed

In [116]:
# Loading the last five rows 
df.tail(20)

,Student_ID,Name,Age,Gender,Department,Attendance,Study_Hours,Assignment_Score,Exam_Score,City,Enrollment_Date,Fee_Status,Placement_Status
41,1042,Pallavi,21,Male,Data Science,96.1,7.4,93,99,Hyderabad,2026-05-08,Paid,Placed
42,1043,Karthik,22,Female,AI,81.5,7.5,74,97,Chennai,2026-05-11,Paid,Not Placed
43,1044,Sowmya,22,Female,Cloud,78.9,NaN,90,88,Hyderabad,2026-05-14,Paid,Not Placed
44,1045,Surya,23,Female,AI,88.0,1.8,96,80,Bengaluru,2026-05-17,Pending,Not Placed
45,1046,Ishita,23,Male,Python,88.7,3.6,49,69,Visakhapatnam,2026-05-20,Paid,Not Placed
46,1047,Manoj,20,Female,AI,94.8,5.3,56,86,Hyderabad,2026-05-23,Paid,Placed
47,1048,Neha,20,Male,Data Science,75.1,3.8,60,70,Chennai,2026-05-26,Pending,Placed
48,1049,Abhishek,21,Male,Data Science,83.5,7.3,70,99,Chennai,2026-05-29,Paid,Placed
49,1050,Sravani,20,Female,AI,85.7,3.4,70,70,Hyderabad,2026-06-01,Pending,Not Placed
50,1051,Lokesh,22,Female,Cloud,91.8,8.3,92,99,Visakhapatnam,2026-06-04,Paid,Not Placed
51,1052,Anusha,23,Male,NaN,69.4,4.7,65,77,Hyderabad,2026-06-07,Pending,Not Placed
52,1053,Chandu,20,Male,Cloud,98.8,7.4,83,99,Chennai,2026-06-10,Paid,Not Placed
53,1054,Ramya,20,Female,Cloud,82.6,2.9,80,78,Vijayawada,2026-06-13,Pending,Placed
54,1055,Yashwanth,21,Female,Data Science,76.7,4.4,77,75,Bengaluru,2026-06-16,Paid,Not Placed
55,1056,Bhargavi,21,Female,Cloud,95.4,6.4,74,99,Chennai,2026-06-19,Pending,Not Placed
56,1057,Venkat,22,Male,AI,91.2,2.5,81,64,Hyderabad,2026-06-22,Paid,Not Placed
57,1058,Sahithi,23,Male,AI,97.5,2.4,67,56,Bengaluru,2026-06-25,Paid,Not Placed
58,1059,Akash,21,Male,AI,78.3,8.3,54,99,Hyderabad,2026-06-28,Pending,Placed
59,1060,Madhavi,20,Male,AI,85.1,6.5,98,99,Hyderabad,2026-07-01,Paid,Placed
60,1012,Manoj,21,Male,Cloud,80.5,2.0,97,73,Chennai,2026-02-07,Paid,Placed

In [117]:
# info
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 61 entries, 0 to 60
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Student_ID        61 non-null     int64
 1   Name              61 non-null     str
 2   Age               61 non-null     int64
 3   Gender            61 non-null     str
 4   Department        60 non-null     str
 5   Attendance        59 non-null     float64
 6   Study_Hours       59 non-null     float64
 7   Assignment_Score  61 non-null     int64
 8   Exam_Score        61 non-null     int64
 9   City              61 non-null     str
 10  Enrollment_Date   61 non-null     str
 11  Fee_Status        61 non-null     str
 12  Placement_Status  61 non-null     str
dtypes: float64(2), int64(4), str(7)
memory usage: 6.3 KB

In [118]:
df.shape

(61, 13)

In [119]:
df.size

793

In [120]:
print(df.columns.tolist())

['Student_ID', 'Name', 'Age', 'Gender', 'Department', 'Attendance', 'Study_Hours', 'Assignment_Score', 'Exam_Score', 'City', 'Enrollment_Date', 'Fee_Status', 'Placement_Status']

In [121]:
df.dtypes

Student_ID            int64
Name                    str
Age                   int64
Gender                  str
Department              str
Attendance          float64
Study_Hours         float64
Assignment_Score      int64
Exam_Score            int64
City                    str
Enrollment_Date         str
Fee_Status              str
Placement_Status        str
dtype: object

In [122]:
print("Summary statistics : ")
display(df.select_dtypes(include="number").describe())

Summary statistics :

,Student_ID,Age,Attendance,Study_Hours,Assignment_Score,Exam_Score
count,61.000000,61.000000,59.000000,59.000000,61.000000,61.000000
mean,1030.196721,21.688525,86.084746,4.633898,72.688525,80.147541
std,17.479340,1.297960,8.569328,2.084475,15.941080,14.473926
min,1001.000000,20.000000,68.600000,1.500000,45.000000,53.000000
25%,1015.000000,21.000000,79.150000,2.950000,60.000000,70.000000
50%,1030.000000,22.000000,85.100000,4.300000,72.000000,80.000000
75%,1045.000000,23.000000,94.450000,6.300000,84.000000,95.000000
max,1060.000000,24.000000,98.900000,8.400000,98.000000,99.000000

In [123]:
print("unique Department : ")
print(df["Department"].unique())

unique Department :
<StringArray>
['Data Science', 'Cloud', 'Python', 'AI', ' ai ', 'data science', 'python ',
 nan]
Length: 8, dtype: str

In [124]:
print("Department Count : ")
print(df["Department"].value_counts)

Department Count :
<bound method IndexOpsMixin.value_counts of 0     Data Science
1            Cloud
2           Python
3     Data Science
4               AI
          ...
56              AI
57              AI
58              AI
59              AI
60           Cloud
Name: Department, Length: 61, dtype: str>

In [125]:
print("Exam Scoure : ")
print(df["Exam_Score"])

Exam Scoure :
0     78
1     99
2     70
3     64
4     76
      ..
56    64
57    56
58    99
59    99
60    73
Name: Exam_Score, Length: 61, dtype: int64

In [126]:
print(df[["Name", "Department", "Exam_Score"]])

       Name    Department  Exam_Score
0      Ravi  Data Science          78
1     Priya         Cloud          99
2      Arun        Python          70
3     Meena  Data Science          64
4     Kiran            AI          76
..      ...           ...         ...
56   Venkat            AI          64
57  Sahithi            AI          56
58    Akash            AI          99
59  Madhavi            AI          99
60    Manoj         Cloud          73

[61 rows x 3 columns]

In [127]:
print("First Row : ")
display(df.loc[0])

First Row :

Student_ID                   1001
Name                         Ravi
Age                            21
Gender                     Female
Department           Data Science
Attendance                   84.0
Study_Hours                   5.5
Assignment_Score               63
Exam_Score                     78
City                Visakhapatnam
Enrollment_Date        2026-01-05
Fee_Status                   Paid
Placement_Status           Placed
Name: 0, dtype: object

In [128]:
display(df.loc[0 : 5,["Name","Exam_Score"]])
# loc - lobel-based indexing here the lable index is 0 so row with 0 as label to 5 are displayed

     Name  Exam_Score
0    Ravi          78
1   Priya          99
2    Arun          70
3   Meena          64
4   Kiran          76
5  Suresh          77

In [129]:
# Wednesday class
# iloc -> Integer - based indexing 
df.iloc[0] #first row

Student_ID                   1001
Name                         Ravi
Age                            21
Gender                     Female
Department           Data Science
Attendance                   84.0
Study_Hours                   5.5
Assignment_Score               63
Exam_Score                     78
City                Visakhapatnam
Enrollment_Date        2026-01-05
Fee_Status                   Paid
Placement_Status           Placed
Name: 0, dtype: object

In [130]:
print(df.iloc[0 : 5,0 : 4])

   Student_ID   Name  Age  Gender
0        1001   Ravi   21  Female
1        1002  Priya   23    Male
2        1003   Arun   23  Female
3        1004  Meena   21    Male
4        1005  Kiran   22    Male

In [131]:
display(df.iloc[0:5,0:4]) # it returns a table in structured format

   Student_ID   Name  Age  Gender
0        1001   Ravi   21  Female
1        1002  Priya   23    Male
2        1003   Arun   23  Female
3        1004  Meena   21    Male
4        1005  Kiran   22    Male

In [132]:
# Filtering 
print("Students with exam_score greather than 80 : ")
display(df[df["Exam_Score"] > 80])

Students with exam_score greather than 80 :

,Student_ID,Name,Age,Gender,Department,Attendance,Study_Hours,Assignment_Score,Exam_Score,City,Enrollment_Date,Fee_Status,Placement_Status
1,1002,Priya,23,Male,Cloud,76.1,8.4,61,99,Chennai,2026-01-08,Paid,Placed
7,1008,Rahul,20,Male,ai,76.6,4.1,97,91,Vijayawada,2026-01-26,Pending,Placed
9,1010,Rahul,22,Female,Python,94.2,7.4,53,84,Bengaluru,2026-02-01,Paid,Not Placed
10,1011,Sneha,20,Female,AI,94.5,8.0,56,94,Visakhapatnam,2026-02-04,Paid,Placed
13,1014,Naveen,23,Male,data science,94.4,6.2,45,82,Bengaluru,2026-02-13,Paid,Placed
14,1015,Pooja,24,Male,AI,97.0,4.0,91,96,Visakhapatnam,2026-02-16,Paid,Placed
16,1017,Swathi,20,Male,AI,88.7,3.6,76,91,Visakhapatnam,2026-02-22,Paid,Placed
18,1019,Keerthi,21,Male,Data Science,79.5,7.4,92,99,Chennai,2026-02-28,Paid,Not Placed
20,1021,Lakshmi,23,Female,Data Science,98.2,6.5,84,99,Bengaluru,2026-03-06,Paid,Placed
21,1022,Varun,21,Male,AI,76.8,5.4,89,88,Visakhapatnam,2026-03-09,Pending,Placed
22,1023,Asha,23,Female,AI,77.5,3.6,97,84,Chennai,2026-03-12,Paid,Placed
25,1026,Sanjana,20,Male,Python,98.8,5.8,83,98,Vijayawada,2026-03-21,Pending,Placed
28,1029,Tarun,21,Male,Data Science,83.3,5.9,73,95,Hyderabad,2026-03-30,Paid,Not Placed
31,1032,Deepika,20,Male,AI,91.1,4.3,70,82,Bengaluru,2026-04-08,Paid,Placed
33,1034,Mounika,22,Male,Cloud,77.5,7.7,95,99,Bengaluru,2026-04-14,Pending,Not Placed
35,1036,Harini,22,Female,python,83.8,5.6,66,88,Chennai,2026-04-20,Paid,Placed
37,1038,Shreya,23,Female,AI,75.8,6.2,58,84,Bengaluru,2026-04-26,Paid,Not Placed
38,1039,Karthik,22,Male,Python,86.3,3.8,72,84,Hyderabad,2026-04-29,Paid,Not Placed
40,1041,Rakesh,22,Male,AI,83.1,8.4,91,99,Hyderabad,2026-05-05,Paid,Placed
41,1042,Pallavi,21,Male,Data Science,96.1,7.4,93,99,Hyderabad,2026-05-08,Paid,Placed
42,1043,Karthik,22,Female,AI,81.5,7.5,74,97,Chennai,2026-05-11,Paid,Not Placed
43,1044,Sowmya,22,Female,Cloud,78.9,NaN,90,88,Hyderabad,2026-05-14,Paid,Not Placed
46,1047,Manoj,20,Female,AI,94.8,5.3,56,86,Hyderabad,2026-05-23,Paid,Placed
48,1049,Abhishek,21,Male,Data Science,83.5,7.3,70,99,Chennai,2026-05-29,Paid,Placed
50,1051,Lokesh,22,Female,Cloud,91.8,8.3,92,99,Visakhapatnam,2026-06-04,Paid,Not Placed
52,1053,Chandu,20,Male,Cloud,98.8,7.4,83,99,Chennai,2026-06-10,Paid,Not Placed
55,1056,Bhargavi,21,Female,Cloud,95.4,6.4,74,99,Chennai,2026-06-19,Pending,Not Placed
58,1059,Akash,21,Male,AI,78.3,8.3,54,99,Hyderabad,2026-06-28,Pending,Placed
59,1060,Madhavi,20,Male,AI,85.1,6.5,98,99,Hyderabad,2026-07-01,Paid,Placed

In [133]:
# print students with attendance greather than 85 
display(df[df['Attendance'] > 85])

,Student_ID,Name,Age,Gender,Department,Attendance,Study_Hours,Assignment_Score,Exam_Score,City,Enrollment_Date,Fee_Status,Placement_Status
2,1003,Arun,23,Female,Python,98.9,2.0,63,70,Hyderabad,2026-01-11,Paid,Placed
3,1004,Meena,21,Male,Data Science,97.9,3.6,72,64,Visakhapatnam,2026-01-14,Paid,Not Placed
5,1006,Suresh,20,Female,AI,95.4,3.4,81,77,Chennai,2026-01-20,Paid,Not Placed
8,1009,Divya,20,Female,Data Science,89.7,4.3,67,77,Vijayawada,2026-01-29,Paid,Not Placed
9,1010,Rahul,22,Female,Python,94.2,7.4,53,84,Bengaluru,2026-02-01,Paid,Not Placed
10,1011,Sneha,20,Female,AI,94.5,8.0,56,94,Visakhapatnam,2026-02-04,Paid,Placed
12,1013,Kavya,21,Male,Python,95.5,3.0,45,59,Hyderabad,2026-02-10,Paid,Not Placed
13,1014,Naveen,23,Male,data science,94.4,6.2,45,82,Bengaluru,2026-02-13,Paid,Placed
14,1015,Pooja,24,Male,AI,97.0,4.0,91,96,Visakhapatnam,2026-02-16,Paid,Placed
15,1016,Harish,20,Male,AI,92.3,3.3,78,66,Bengaluru,2026-02-19,Paid,Not Placed
16,1017,Swathi,20,Male,AI,88.7,3.6,76,91,Visakhapatnam,2026-02-22,Paid,Placed
19,1020,Rohit,24,Male,AI,97.1,2.5,69,70,Visakhapatnam,2026-03-03,Paid,Not Placed
20,1021,Lakshmi,23,Female,Data Science,98.2,6.5,84,99,Bengaluru,2026-03-06,Paid,Placed
25,1026,Sanjana,20,Male,Python,98.8,5.8,83,98,Vijayawada,2026-03-21,Pending,Placed
31,1032,Deepika,20,Male,AI,91.1,4.3,70,82,Bengaluru,2026-04-08,Paid,Placed
32,1033,Pranav,23,Male,AI,90.3,1.9,60,53,Bengaluru,2026-04-11,Paid,Not Placed
36,1037,Ganesh,23,Male,AI,87.7,4.6,73,80,Vijayawada,2026-04-23,Paid,Placed
38,1039,Karthik,22,Male,Python,86.3,3.8,72,84,Hyderabad,2026-04-29,Paid,Not Placed
39,1040,Lavanya,23,Female,Data Science,98.3,2.6,49,54,Hyderabad,2026-05-02,Paid,Not Placed
41,1042,Pallavi,21,Male,Data Science,96.1,7.4,93,99,Hyderabad,2026-05-08,Paid,Placed
44,1045,Surya,23,Female,AI,88.0,1.8,96,80,Bengaluru,2026-05-17,Pending,Not Placed
45,1046,Ishita,23,Male,Python,88.7,3.6,49,69,Visakhapatnam,2026-05-20,Paid,Not Placed
46,1047,Manoj,20,Female,AI,94.8,5.3,56,86,Hyderabad,2026-05-23,Paid,Placed
49,1050,Sravani,20,Female,AI,85.7,3.4,70,70,Hyderabad,2026-06-01,Pending,Not Placed
50,1051,Lokesh,22,Female,Cloud,91.8,8.3,92,99,Visakhapatnam,2026-06-04,Paid,Not Placed
52,1053,Chandu,20,Male,Cloud,98.8,7.4,83,99,Chennai,2026-06-10,Paid,Not Placed
55,1056,Bhargavi,21,Female,Cloud,95.4,6.4,74,99,Chennai,2026-06-19,Pending,Not Placed
56,1057,Venkat,22,Male,AI,91.2,2.5,81,64,Hyderabad,2026-06-22,Paid,Not Placed
57,1058,Sahithi,23,Male,AI,97.5,2.4,67,56,Bengaluru,2026-06-25,Paid,Not Placed
59,1060,Madhavi,20,Male,AI,85.1,6.5,98,99,Hyderabad,2026-07-01,Paid,Placed

In [134]:
# print students with attendence greather than 85 and exam_Score greather than 80
display(df[(df['Exam_Score'] > 80) & (df['Attendance'] > 85)])

,Student_ID,Name,Age,Gender,Department,Attendance,Study_Hours,Assignment_Score,Exam_Score,City,Enrollment_Date,Fee_Status,Placement_Status
9,1010,Rahul,22,Female,Python,94.2,7.4,53,84,Bengaluru,2026-02-01,Paid,Not Placed
10,1011,Sneha,20,Female,AI,94.5,8.0,56,94,Visakhapatnam,2026-02-04,Paid,Placed
13,1014,Naveen,23,Male,data science,94.4,6.2,45,82,Bengaluru,2026-02-13,Paid,Placed
14,1015,Pooja,24,Male,AI,97.0,4.0,91,96,Visakhapatnam,2026-02-16,Paid,Placed
16,1017,Swathi,20,Male,AI,88.7,3.6,76,91,Visakhapatnam,2026-02-22,Paid,Placed
20,1021,Lakshmi,23,Female,Data Science,98.2,6.5,84,99,Bengaluru,2026-03-06,Paid,Placed
25,1026,Sanjana,20,Male,Python,98.8,5.8,83,98,Vijayawada,2026-03-21,Pending,Placed
31,1032,Deepika,20,Male,AI,91.1,4.3,70,82,Bengaluru,2026-04-08,Paid,Placed
38,1039,Karthik,22,Male,Python,86.3,3.8,72,84,Hyderabad,2026-04-29,Paid,Not Placed
41,1042,Pallavi,21,Male,Data Science,96.1,7.4,93,99,Hyderabad,2026-05-08,Paid,Placed
46,1047,Manoj,20,Female,AI,94.8,5.3,56,86,Hyderabad,2026-05-23,Paid,Placed
50,1051,Lokesh,22,Female,Cloud,91.8,8.3,92,99,Visakhapatnam,2026-06-04,Paid,Not Placed
52,1053,Chandu,20,Male,Cloud,98.8,7.4,83,99,Chennai,2026-06-10,Paid,Not Placed
55,1056,Bhargavi,21,Female,Cloud,95.4,6.4,74,99,Chennai,2026-06-19,Pending,Not Placed
59,1060,Madhavi,20,Male,AI,85.1,6.5,98,99,Hyderabad,2026-07-01,Paid,Placed

In [135]:
# print studens in AI or data Science 
display(df[df['Department'].isin(['Data Science','AI'])])

,Student_ID,Name,Age,Gender,Department,Attendance,Study_Hours,Assignment_Score,Exam_Score,City,Enrollment_Date,Fee_Status,Placement_Status
0,1001,Ravi,21,Female,Data Science,84.0,5.5,63,78,Visakhapatnam,2026-01-05,Paid,Placed
3,1004,Meena,21,Male,Data Science,97.9,3.6,72,64,Visakhapatnam,2026-01-14,Paid,Not Placed
4,1005,Kiran,22,Male,AI,NaN,2.8,70,76,Vijayawada,2026-01-17,Paid,Placed
5,1006,Suresh,20,Female,AI,95.4,3.4,81,77,Chennai,2026-01-20,Paid,Not Placed
6,1007,Anjali,24,Female,AI,73.8,4.9,70,74,Hyderabad,2026-01-23,Paid,Placed
8,1009,Divya,20,Female,Data Science,89.7,4.3,67,77,Vijayawada,2026-01-29,Paid,Not Placed
10,1011,Sneha,20,Female,AI,94.5,8.0,56,94,Visakhapatnam,2026-02-04,Paid,Placed
14,1015,Pooja,24,Male,AI,97.0,4.0,91,96,Visakhapatnam,2026-02-16,Paid,Placed
15,1016,Harish,20,Male,AI,92.3,3.3,78,66,Bengaluru,2026-02-19,Paid,Not Placed
16,1017,Swathi,20,Male,AI,88.7,3.6,76,91,Visakhapatnam,2026-02-22,Paid,Placed
17,1018,Ajay,22,Male,Data Science,NaN,3.8,98,73,Visakhapatnam,2026-02-25,Pending,Placed
18,1019,Keerthi,21,Male,Data Science,79.5,7.4,92,99,Chennai,2026-02-28,Paid,Not Placed
19,1020,Rohit,24,Male,AI,97.1,2.5,69,70,Visakhapatnam,2026-03-03,Paid,Not Placed
20,1021,Lakshmi,23,Female,Data Science,98.2,6.5,84,99,Bengaluru,2026-03-06,Paid,Placed
21,1022,Varun,21,Male,AI,76.8,5.4,89,88,Visakhapatnam,2026-03-09,Pending,Placed
22,1023,Asha,23,Female,AI,77.5,3.6,97,84,Chennai,2026-03-12,Paid,Placed
23,1024,Dinesh,22,Female,Data Science,83.1,4.4,45,63,Chennai,2026-03-15,Paid,Not Placed
24,1025,Teja,22,Female,Data Science,81.9,3.3,60,63,Bengaluru,2026-03-18,Paid,Not Placed
26,1027,sneha,24,Male,AI,73.5,2.1,49,57,Vijayawada,2026-03-24,Pending,Not Placed
27,1028,Bhavya,23,Male,Data Science,68.6,1.5,66,54,Visakhapatnam,2026-03-27,Paid,Not Placed
28,1029,Tarun,21,Male,Data Science,83.3,5.9,73,95,Hyderabad,2026-03-30,Paid,Not Placed
29,1030,Nisha,22,Female,AI,73.5,NaN,47,61,Visakhapatnam,2026-04-02,Paid,Not Placed
30,1031,Sai,20,Male,Data Science,79.4,2.0,56,63,Bengaluru,2026-04-05,Paid,Not Placed
31,1032,Deepika,20,Male,AI,91.1,4.3,70,82,Bengaluru,2026-04-08,Paid,Placed
32,1033,Pranav,23,Male,AI,90.3,1.9,60,53,Bengaluru,2026-04-11,Paid,Not Placed
36,1037,Ganesh,23,Male,AI,87.7,4.6,73,80,Vijayawada,2026-04-23,Paid,Placed
37,1038,Shreya,23,Female,AI,75.8,6.2,58,84,Bengaluru,2026-04-26,Paid,Not Placed
39,1040,Lavanya,23,Female,Data Science,98.3,2.6,49,54,Hyderabad,2026-05-02,Paid,Not Placed
40,1041,Rakesh,22,Male,AI,83.1,8.4,91,99,Hyderabad,2026-05-05,Paid,Placed
41,1042,Pallavi,21,Male,Data Science,96.1,7.4,93,99,Hyderabad,2026-05-08,Paid,Placed
42,1043,Karthik,22,Female,AI,81.5,7.5,74,97,Chennai,2026-05-11,Paid,Not Placed
44,1045,Surya,23,Female,AI,88.0,1.8,96,80,Bengaluru,2026-05-17,Pending,Not Placed
46,1047,Manoj,20,Female,AI,94.8,5.3,56,86,Hyderabad,2026-05-23,Paid,Placed
47,1048,Neha,20,Male,Data Science,75.1,3.8,60,70,Chennai,2026-05-26,Pending,Placed
48,1049,Abhishek,21,Male,Data Science,83.5,7.3,70,99,Chennai,2026-05-29,Paid,Placed
49,1050,Sravani,20,Female,AI,85.7,3.4,70,70,Hyderabad,2026-06-01,Pending,Not Placed
54,1055,Yashwanth,21,Female,Data Science,76.7,4.4,77,75,Bengaluru,2026-06-16,Paid,Not Placed
56,1057,Venkat,22,Male,AI,91.2,2.5,81,64,Hyderabad,2026-06-22,Paid,Not Placed
57,1058,Sahithi,23,Male,AI,97.5,2.4,67,56,Bengaluru,2026-06-25,Paid,Not Placed
58,1059,Akash,21,Male,AI,78.3,8.3,54,99,Hyderabad,2026-06-28,Pending,Placed
59,1060,Madhavi,20,Male,AI,85.1,6.5,98,99,Hyderabad,2026-07-01,Paid,Placed

In [136]:
# sorting the values 
display(df.sort_values(by='Attendance',ascending=True).head(10))

,Student_ID,Name,Age,Gender,Department,Attendance,Study_Hours,Assignment_Score,Exam_Score,City,Enrollment_Date,Fee_Status,Placement_Status
27,1028,Bhavya,23,Male,Data Science,68.6,1.5,66,54,Visakhapatnam,2026-03-27,Paid,Not Placed
51,1052,Anusha,23,Male,NaN,69.4,4.7,65,77,Hyderabad,2026-06-07,Pending,Not Placed
29,1030,Nisha,22,Female,AI,73.5,NaN,47,61,Visakhapatnam,2026-04-02,Paid,Not Placed
26,1027,sneha,24,Male,AI,73.5,2.1,49,57,Vijayawada,2026-03-24,Pending,Not Placed
6,1007,Anjali,24,Female,AI,73.8,4.9,70,74,Hyderabad,2026-01-23,Paid,Placed
47,1048,Neha,20,Male,Data Science,75.1,3.8,60,70,Chennai,2026-05-26,Pending,Placed
37,1038,Shreya,23,Female,AI,75.8,6.2,58,84,Bengaluru,2026-04-26,Paid,Not Placed
1,1002,Priya,23,Male,Cloud,76.1,8.4,61,99,Chennai,2026-01-08,Paid,Placed
7,1008,Rahul,20,Male,ai,76.6,4.1,97,91,Vijayawada,2026-01-26,Pending,Placed
54,1055,Yashwanth,21,Female,Data Science,76.7,4.4,77,75,Bengaluru,2026-06-16,Paid,Not Placed

In [137]:
# Add and Modify Columns 
df.shape
# adding a pass or fail result column based on exam_score 
# .copy() function copies all the dataset 
work = df.copy()
work['Passed'] = work['Exam_Score'] >= 50
work['Total_Score'] = work['Exam_Score'] + work['Assignment_Score']
work['Average_Score'] = work[['Exam_Score','Assignment_Score']].mean(axis=1)
# Display , Assignment_Score,Exam_Score,Total_Score,Average_Score,Passed
display(work[['Name','Assignment_Score','Exam_Score','Total_Score','Average_Score','Passed']].head())

    Name  Assignment_Score  Exam_Score  Total_Score  Average_Score  Passed
0   Ravi                63          78          141           70.5    True
1  Priya                61          99          160           80.0    True
2   Arun                63          70          133           66.5    True
3  Meena                72          64          136           68.0    True
4  Kiran                70          76          146           73.0    True

In [138]:
# Creating a Feature with where until now we created normally now we are using where() method 
# Featuring Engineering -> It means adding new features by using existing features 
work['Performace_Level'] = np.where(
    work['Exam_Score'] >= 85, "Excellent",
    np.where(work['Exam_Score'] >= 70 , "Good","Needs_Improvement")
)
display(work[['Name',"Exam_Score","Performace_Level"]].head(10))

        Name  Exam_Score   Performace_Level
0       Ravi          78               Good
1      Priya          99          Excellent
2       Arun          70               Good
3      Meena          64  Needs_Improvement
4      Kiran          76               Good
5     Suresh          77               Good
6     Anjali          74               Good
7      Rahul          91          Excellent
8      Divya          77               Good
9    Rahul            84               Good

In [139]:
# Renaming a Column using .rename() function 
df = df.rename(
    columns={
        "Exam_Score" : "Final_Exam_Score",
        "Study_Hours" : "Daily_Study_Hours"
    }
)
display(df.head())

,Student_ID,Name,Age,Gender,Department,Attendance,Daily_Study_Hours,Assignment_Score,Final_Exam_Score,City,Enrollment_Date,Fee_Status,Placement_Status
0,1001,Ravi,21,Female,Data Science,84.0,5.5,63,78,Visakhapatnam,2026-01-05,Paid,Placed
1,1002,Priya,23,Male,Cloud,76.1,8.4,61,99,Chennai,2026-01-08,Paid,Placed
2,1003,Arun,23,Female,Python,98.9,2.0,63,70,Hyderabad,2026-01-11,Paid,Placed
3,1004,Meena,21,Male,Data Science,97.9,3.6,72,64,Visakhapatnam,2026-01-14,Paid,Not Placed
4,1005,Kiran,22,Male,AI,NaN,2.8,70,76,Vijayawada,2026-01-17,Paid,Placed

In [140]:
# Removing columns using .drop() function 
# .axis = 1 / Remove columns 
# .axis = 0 / Remove Rows 
example = work.drop(columns=['Total_Score'])
display(example.head())
example = work.drop(index=[0,1])
display(example.head())

,Student_ID,Name,Age,Gender,Department,Attendance,Study_Hours,Assignment_Score,Exam_Score,City,Enrollment_Date,Fee_Status,Placement_Status,Passed,Average_Score,Performace_Level
0,1001,Ravi,21,Female,Data Science,84.0,5.5,63,78,Visakhapatnam,2026-01-05,Paid,Placed,True,70.5,Good
1,1002,Priya,23,Male,Cloud,76.1,8.4,61,99,Chennai,2026-01-08,Paid,Placed,True,80.0,Excellent
2,1003,Arun,23,Female,Python,98.9,2.0,63,70,Hyderabad,2026-01-11,Paid,Placed,True,66.5,Good
3,1004,Meena,21,Male,Data Science,97.9,3.6,72,64,Visakhapatnam,2026-01-14,Paid,Not Placed,True,68.0,Needs_Improvement
4,1005,Kiran,22,Male,AI,NaN,2.8,70,76,Vijayawada,2026-01-17,Paid,Placed,True,73.0,Good

,Student_ID,Name,Age,Gender,Department,Attendance,Study_Hours,Assignment_Score,Exam_Score,City,Enrollment_Date,Fee_Status,Placement_Status,Passed,Total_Score,Average_Score,Performace_Level
2,1003,Arun,23,Female,Python,98.9,2.0,63,70,Hyderabad,2026-01-11,Paid,Placed,True,133,66.5,Good
3,1004,Meena,21,Male,Data Science,97.9,3.6,72,64,Visakhapatnam,2026-01-14,Paid,Not Placed,True,136,68.0,Needs_Improvement
4,1005,Kiran,22,Male,AI,NaN,2.8,70,76,Vijayawada,2026-01-17,Paid,Placed,True,146,73.0,Good
5,1006,Suresh,20,Female,AI,95.4,3.4,81,77,Chennai,2026-01-20,Paid,Not Placed,True,158,79.0,Good
6,1007,Anjali,24,Female,AI,73.8,4.9,70,74,Hyderabad,2026-01-23,Paid,Placed,True,144,72.0,Good

In [141]:
# Handling the missing values by using mean ,mode , median 
print("Find how many missing values are there in the dataset : ")
print(df.isna().sum())
print("Total : ",df.isna().sum().sum())

"""

    # using fill na 
    df['Attendance'].fillna(df['Attendance'].mean(),inplace=True)

"""
# dropna 
# if you do inplace=True for anything it will effect the original dataset
complete_rows = df.dropna() # removes rows containing null values 
print(complete_rows.shape)

Find how many missing values are there in the dataset :
Student_ID           0
Name                 0
Age                  0
Gender               0
Department           1
Attendance           2
Daily_Study_Hours    2
Assignment_Score     0
Final_Exam_Score     0
City                 0
Enrollment_Date      0
Fee_Status           0
Placement_Status     0
dtype: int64
Total :  5
(56, 13)

In [142]:
# filling the dataset using .fillna() 
# it will target the missing values only 
filled = work.copy()
display(filled.head(10))
filled['Attendance'] = filled['Attendance'].fillna(filled['Attendance'].median())
filled['Study_Hours'] = filled['Study_Hours'].fillna(filled['Study_Hours'].median())
filled['Department'] = filled['Department'].fillna("unknown")
display(filled.head(10)) # observe index 4 the attendeance of kiran is filled with 85.1 which is median value

,Student_ID,Name,Age,Gender,Department,Attendance,Study_Hours,Assignment_Score,Exam_Score,City,Enrollment_Date,Fee_Status,Placement_Status,Passed,Total_Score,Average_Score,Performace_Level
0,1001,Ravi,21,Female,Data Science,84.0,5.5,63,78,Visakhapatnam,2026-01-05,Paid,Placed,True,141,70.5,Good
1,1002,Priya,23,Male,Cloud,76.1,8.4,61,99,Chennai,2026-01-08,Paid,Placed,True,160,80.0,Excellent
2,1003,Arun,23,Female,Python,98.9,2.0,63,70,Hyderabad,2026-01-11,Paid,Placed,True,133,66.5,Good
3,1004,Meena,21,Male,Data Science,97.9,3.6,72,64,Visakhapatnam,2026-01-14,Paid,Not Placed,True,136,68.0,Needs_Improvement
4,1005,Kiran,22,Male,AI,NaN,2.8,70,76,Vijayawada,2026-01-17,Paid,Placed,True,146,73.0,Good
5,1006,Suresh,20,Female,AI,95.4,3.4,81,77,Chennai,2026-01-20,Paid,Not Placed,True,158,79.0,Good
6,1007,Anjali,24,Female,AI,73.8,4.9,70,74,Hyderabad,2026-01-23,Paid,Placed,True,144,72.0,Good
7,1008,Rahul,20,Male,ai,76.6,4.1,97,91,Vijayawada,2026-01-26,Pending,Placed,True,188,94.0,Excellent
8,1009,Divya,20,Female,Data Science,89.7,4.3,67,77,Vijayawada,2026-01-29,Paid,Not Placed,True,144,72.0,Good
9,1010,Rahul,22,Female,Python,94.2,7.4,53,84,Bengaluru,2026-02-01,Paid,Not Placed,True,137,68.5,Good

,Student_ID,Name,Age,Gender,Department,Attendance,Study_Hours,Assignment_Score,Exam_Score,City,Enrollment_Date,Fee_Status,Placement_Status,Passed,Total_Score,Average_Score,Performace_Level
0,1001,Ravi,21,Female,Data Science,84.0,5.5,63,78,Visakhapatnam,2026-01-05,Paid,Placed,True,141,70.5,Good
1,1002,Priya,23,Male,Cloud,76.1,8.4,61,99,Chennai,2026-01-08,Paid,Placed,True,160,80.0,Excellent
2,1003,Arun,23,Female,Python,98.9,2.0,63,70,Hyderabad,2026-01-11,Paid,Placed,True,133,66.5,Good
3,1004,Meena,21,Male,Data Science,97.9,3.6,72,64,Visakhapatnam,2026-01-14,Paid,Not Placed,True,136,68.0,Needs_Improvement
4,1005,Kiran,22,Male,AI,85.1,2.8,70,76,Vijayawada,2026-01-17,Paid,Placed,True,146,73.0,Good
5,1006,Suresh,20,Female,AI,95.4,3.4,81,77,Chennai,2026-01-20,Paid,Not Placed,True,158,79.0,Good
6,1007,Anjali,24,Female,AI,73.8,4.9,70,74,Hyderabad,2026-01-23,Paid,Placed,True,144,72.0,Good
7,1008,Rahul,20,Male,ai,76.6,4.1,97,91,Vijayawada,2026-01-26,Pending,Placed,True,188,94.0,Excellent
8,1009,Divya,20,Female,Data Science,89.7,4.3,67,77,Vijayawada,2026-01-29,Paid,Not Placed,True,144,72.0,Good
9,1010,Rahul,22,Female,Python,94.2,7.4,53,84,Bengaluru,2026-02-01,Paid,Not Placed,True,137,68.5,Good

In [143]:
# Duplicates 
# .duplicated() -> identifies duplicate rows 
# .drop_duplicates() -> removes them
display(df[df.duplicated(keep=False)])
df = df.drop_duplicates()
df.shape

,Student_ID,Name,Age,Gender,Department,Attendance,Daily_Study_Hours,Assignment_Score,Final_Exam_Score,City,Enrollment_Date,Fee_Status,Placement_Status
11,1012,Manoj,21,Male,Cloud,80.5,2.0,97,73,Chennai,2026-02-07,Paid,Placed
60,1012,Manoj,21,Male,Cloud,80.5,2.0,97,73,Chennai,2026-02-07,Paid,Placed

(60, 13)

In [ ]:
# String operations 
# str.strip() -> removes white spaces 
# str.lower() -> converts to lower case 
# str.upper() -> converts to upper case 
# str.title() -> converts to tile case 
# str.contains() -> search text 

name = pd.Series(['Ravi  ','PRIYA','Arun','   Meena'])

print('Clean Spaces : ')
display(name.str.strip())

print('Lower Case : ')
display(name.str.lower())

print('Upper Case : ')
display(name.str.upper())

print('Title Case : ')
display(name.str.title())

Clean Spaces :

0     Ravi
1    PRIYA
2     Arun
3    Meena
dtype: str

Lower Case :

0      ravi
1       priya
2        arun
3       meena
dtype: str

Upper Case :

0      RAVI
1       PRIYA
2        ARUN
3       MEENA
dtype: str

Title Case :

0      Ravi
1       Priya
2        Arun
3       Meena
dtype: str